### ISSUE TITLE
Publish latest fix to npm

### ISSUE THREAD

**Issue by CarbonAlabel** [matthew1232/discord-webhook-node#13]
The fix from https://github.com/matthew1232/discord-webhook-node/commit/219126d21f7bae23a890ade110716f30784c0c16 hasn't been published to npm. npm already has a v1.1.1, but that one is from 8 months ago: https://www.npmjs.com/package/discord-webhook-node/v/1.1.1

**Comment by matthew1232** [comment]
Nice catch, it looks like the versions got a little mixed up. The latest version is now published @1.1.6.
