### ISSUE TITLE
ES6 import not possible

### ISSUE THREAD

**Issue by C0kkie** [matthew1232/discord-webhook-node#16]
Hello,

i tried to import the modules like

import { Webhook, MessageBuilder } from 'discord-webhook-node';

but i get the error 

SyntaxError: The requested module 'discord-webhook-node' does not provide an export named 'Webhook'

can you implement this?

**Comment by matthew1232** [comment]
Hello, I added a default object to the module.exports in 1.1.6. Please let me know if this fixes the problem.

**Comment by CarbonAlabel** [comment]
It doesn't work, I'll open a PR to fix it in a bit.
