### ISSUE TITLE
Feature request: passing a buffer to the sendFile method

### ISSUE THREAD

**Issue by Migushthe2nd** [matthew1232/discord-webhook-node#17]
I'd like to pass a buffer, but since `createReadStream` is used a path is required. You could make another method like `sendFileBuffer` and make it accept a buffer and a specified filename.

**Comment by matthew1232** [comment]
The problem is, `createReadStream` doesn't return a buffer, it returns a readable file stream. I tried a lot of different things and couldn't get anything to work without using `createReadStream`.

**Comment by matthew1232** [comment]
Let me know if you find a way and I'll add it, but if you can I'd recommend writing a file with the buffer, sending the file, and then deleting the file.
