### ISSUE TITLE
Set Name for Webhook Post

### ISSUE THREAD

**Issue by Repooc** [matthew1232/discord-webhook-node#18]
I been using something similar to this and I like being able to set the name of the Bot posting with the setName which I think yours lacks.  This is the project and the place in the builder of said function https://github.com/j03b/webhook-discord/blob/master/lib/builder.js#L71  if not, no biggie but thought I'd try yours out due to async/await support

I like this option as I don't want to create multiple webhooks in one channel if I dont have to just so the name can be altered.

**Comment by matthew1232** [comment]
Looks like I accidentally left it out of the documentation (fixing asap) but you can use the Webhook method .setUsername(username) and .setAvatar(avatar_url) to override the defaults for the webhook

example:
```js
const hook = new Webhook(process.env.WEBHOOK_URL);
const IMAGE_URL = 'https://homepages.cae.wisc.edu/~ece533/images/airplane.png';

hook.setUsername('Discord Webhook Node Name');
hook.setAvatar(IMAGE_URL);
```

**Comment by Repooc** [comment]
Ahhh  tyvm... i will prob use this instead then.  Appreciate that.
